# Generated by Django 4.2 on 2023-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_email_alter_candidate_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='profile',
            field=models.IntegerField(default='2'),
        ),
    ]
