# Generated by Django 4.2 on 2023-04-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('candidate', '0005_alter_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='time_online',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='enrollment',
            field=models.ManyToManyField(blank=True, to='enrollment.enrollment'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
